#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-proctitle
Version  : 0.1.2
Release  : 4
URL      : https://pecl.php.net//get/proctitle-0.1.2.tgz
Source0  : https://pecl.php.net//get/proctitle-0.1.2.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : PHP-3.01
Requires: php-proctitle-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
ProcTitle extension
References:
http://bugs.php.net/29479
http://wikipedia.svn.sourceforge.net/viewvc/wikipedia/trunk/extensions/pecl-proctitle/
http://en.wikipedia.org/wiki/User:Midom

%package lib
Summary: lib components for the php-proctitle package.
Group: Libraries

%description lib
lib components for the php-proctitle package.


%prep
%setup -q -n proctitle-0.1.2
cd %{_builddir}/proctitle-0.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20190902/proctitle.so
